<x-ui.workspace :customer="$customer" :tabs="$tabs" current="ai"
                subtitle="AI proposes. People decide. Nothing generated is applied without a second pair of eyes.">
    <x-slot:actions>
        @if ($canGenerate)
            <x-ui.button size="sm" variant="primary" wire:click="startGeneration">Generate form draft</x-ui.button>
        @endif
    </x-slot:actions>

    @error('domain')
        <x-ui.alert tone="danger" class="mb-4">{{ $message }}</x-ui.alert>
    @enderror

    <x-ui.alert tone="info" class="mb-5">
        AI is never the source of truth here. It proposes form structure and prose; it does not compute
        scores, mark attendance, record MMD figures, issue access links or change anybody's permissions.
        Context is assembled from this business's own records only.
    </x-ui.alert>

    <x-ui.table :headings="['Purpose', 'Prompt', 'Stage', 'Generated by', 'Decided by', 'When', '>']">
        @forelse ($generations as $generation)
            <tr wire:key="generation-{{ $generation->id }}" class="hover:bg-slate-50">
                <x-ui.td class="font-medium">{{ Str::headline($generation->purpose->value) }}</x-ui.td>
                <x-ui.td muted>
                    <span class="font-mono text-xs">
                        {{ $generation->promptVersion?->key }} v{{ $generation->promptVersion?->version_number }}
                    </span>
                </x-ui.td>
                <x-ui.td><x-ui.status-badge :status="$generation->status" /></x-ui.td>
                <x-ui.td muted>{{ $generation->generatedBy?->name }}</x-ui.td>
                <x-ui.td muted>{{ $generation->approval?->decidedBy?->name ?? '—' }}</x-ui.td>
                <x-ui.td muted>{{ $generation->generated_at?->format('d M Y H:i') }}</x-ui.td>
                <x-ui.td align="right">
                    <x-ui.button size="sm" :href="route('ai.generations.show', $generation)">Open</x-ui.button>
                </x-ui.td>
            </tr>
        @empty
            <x-ui.empty-row :colspan="7" title="No AI activity for this business"
                            description="Nothing has been asked of a model about this customer." />
        @endforelse
    </x-ui.table>

    <x-ui.modal :show="$generating" title="Generate a form draft" close="$set('generating', false)">
        <form wire:submit="generate" class="space-y-4">
            <x-ui.field label="What is the form for?" required
                        hint="A short brief from you. This is staff-supplied context, not participant text."
                        :error="$errors->first('brief')">
                <x-ui.textarea wire:model="brief" rows="4"
                               placeholder="A short operations intake covering staffing and daily routine." />
            </x-ui.field>

            <x-ui.alert tone="info">
                The model returns a <strong>proposal</strong>. It is validated against a schema, and only
                then can it become a draft — which still needs approval from somebody other than you before
                anything is published.
            </x-ui.alert>

            <div class="flex justify-end gap-2">
                <x-ui.button type="button" wire:click="$set('generating', false)">Cancel</x-ui.button>
                <x-ui.button variant="primary" type="submit">Generate</x-ui.button>
                <x-ui.loading target="generate" label="Asking the model…" />
            </div>
        </form>
    </x-ui.modal>
</x-ui.workspace>
