<div>
    <x-ui.page-header title="AI generations"
                      subtitle="Generate → Validate → Draft → Preview → Approve → Publish. Each stage is distinct and none is skipped." />

    @if ($awaitingCount > 0)
        <x-ui.alert tone="warning" class="mb-4" title="{{ $awaitingCount }} awaiting a decision">
            An AI proposal is applied only after somebody other than the person who asked for it approves it.
        </x-ui.alert>
    @endif

    <x-ui.filters class="mb-4">
        <x-ui.select wire:model.live="status" class="w-auto">
            <option value="all">All stages</option>
            @foreach ($statuses as $value)
                <option value="{{ $value }}">{{ Str::headline($value) }}</option>
            @endforeach
        </x-ui.select>

        <x-ui.select wire:model.live="purpose" class="w-auto">
            <option value="all">All purposes</option>
            @foreach ($purposes as $value)
                <option value="{{ $value }}">{{ Str::headline($value) }}</option>
            @endforeach
        </x-ui.select>

        <x-ui.loading target="status,purpose" />
    </x-ui.filters>

    <x-ui.table :headings="['Customer', 'Purpose', 'Prompt', 'Stage', 'Generated by', 'Decided by', '>']">
        @forelse ($generations as $generation)
            <tr wire:key="generation-{{ $generation->id }}" class="hover:bg-slate-50">
                <x-ui.td class="font-medium">{{ $generation->customer?->name }}</x-ui.td>
                <x-ui.td muted>{{ Str::headline($generation->purpose->value) }}</x-ui.td>
                <x-ui.td muted>
                    <span class="font-mono text-xs">
                        {{ $generation->promptVersion?->key }} v{{ $generation->promptVersion?->version_number }}
                    </span>
                </x-ui.td>
                <x-ui.td><x-ui.status-badge :status="$generation->status" /></x-ui.td>
                <x-ui.td muted>{{ $generation->generatedBy?->name }}</x-ui.td>
                <x-ui.td muted>
                    {{ $generation->approval?->decidedBy?->name ?? '—' }}
                </x-ui.td>
                <x-ui.td align="right">
                    <x-ui.button size="sm" :href="route('ai.generations.show', $generation)">Open</x-ui.button>
                </x-ui.td>
            </tr>
        @empty
            <x-ui.empty-row :colspan="7" title="No AI generations"
                            description="Nothing has been asked of a model yet. Generation starts from a customer's AI tab." />
        @endforelse
    </x-ui.table>

    <div class="mt-4">{{ $generations->links() }}</div>
</div>
