@php use App\Enums\AiGenerationStatus; @endphp

<div>
    <x-ui.page-header :title="'AI generation #'.$generation->id"
                      :subtitle="Str::headline($generation->purpose->value).' for '.$generation->customer?->name"
                      :breadcrumbs="['AI generations' => route('ai.generations'), '#'.$generation->id => null]">
        <x-slot:actions>
            <x-ui.status-badge :status="$generation->status" />

            @if ($generation->status === AiGenerationStatus::Succeeded && $generation->purpose->value === 'form_draft')
                @can('draft', $generation)
                    <x-ui.button size="sm" wire:click="startDraft">Create draft</x-ui.button>
                @endcan
            @endif

            @if ($generation->isAwaitingApproval() && $canDecide)
                <x-ui.button size="sm" variant="primary" wire:click="startDecision">Review</x-ui.button>
            @endif
        </x-slot:actions>
    </x-ui.page-header>

    @error('domain')
        <x-ui.alert tone="danger" class="mb-4">{{ $message }}</x-ui.alert>
    @enderror

    {{-- The self-approval invariant, made legible. --}}
    @if ($generation->isAwaitingApproval() && $viewerIsGenerator)
        <x-ui.alert tone="warning" class="mb-4" title="You cannot decide on your own generation">
            You asked for this output, so somebody else reviews it. This holds for every role, including
            Super Admin — the rule is enforced on the record itself, not only on this screen.
        </x-ui.alert>
    @endif

    <div class="mb-5 grid gap-5 lg:grid-cols-3">
        <x-ui.card title="Provenance" subtitle="What was asked, by whom, of which prompt.">
            <dl class="divide-y divide-line">
                <x-ui.definition term="Customer">
                    @can('customers.view')
                        <a href="{{ route('customers.show', $generation->customer_id) }}" class="hover:underline">
                            {{ $generation->customer?->name }}
                        </a>
                    @else
                        {{ $generation->customer?->name }}
                    @endcan
                </x-ui.definition>
                <x-ui.definition term="Purpose">{{ Str::headline($generation->purpose->value) }}</x-ui.definition>
                <x-ui.definition term="Prompt version">
                    <span class="font-mono text-xs">
                        {{ $generation->promptVersion?->key }} v{{ $generation->promptVersion?->version_number }}
                    </span>
                </x-ui.definition>
                <x-ui.definition term="Model">
                    {{ $generation->promptVersion?->model_identifier ?? 'Configured default' }}
                </x-ui.definition>
                <x-ui.definition term="Generated by">{{ $generation->generatedBy?->name }}</x-ui.definition>
                <x-ui.definition term="Generated at">
                    {{ $generation->generated_at?->format('d M Y H:i') }}
                </x-ui.definition>
                <x-ui.definition term="Tokens used">{{ $generation->tokens_used ?? '—' }}</x-ui.definition>
            </dl>

            <p class="mt-3 border-t border-line pt-3 text-xs text-ink-3">
                Provider credentials are never shown here and are not reachable from this screen.
            </p>
        </x-ui.card>

        <x-ui.card title="Lifecycle" subtitle="Each stage is a separate act." class="lg:col-span-2">
            <ol class="space-y-2.5">
                @php
                    $stages = [
                        ['Generate', 'The provider was called and the attempt recorded.', true],
                        ['Validate', 'Output conformed to the prompt version\'s schema.',
                            in_array($generation->status, [AiGenerationStatus::Succeeded, AiGenerationStatus::AwaitingApproval, AiGenerationStatus::Approved, AiGenerationStatus::Rejected], true)],
                        ['Draft', 'Structure entered the ordinary form engine as a draft.',
                            $generation->resulting_form_version_id !== null],
                        ['Preview', 'A person read it.', $generation->isAwaitingApproval() || $generation->isDecided()],
                        ['Approve', 'A second person signed it off.', $generation->status === AiGenerationStatus::Approved],
                        ['Publish', 'The draft became the live version.',
                            $generation->status === AiGenerationStatus::Approved && $generation->resultingFormVersion?->isPublished()],
                    ];
                @endphp

                @foreach ($stages as [$label, $description, $done])
                    <li class="flex items-start gap-3">
                        <span class="mt-1 h-2 w-2 shrink-0 rounded-full {{ $done ? 'bg-success-wash0' : 'bg-line-strong' }}"
                              aria-hidden="true"></span>
                        <div>
                            <p class="text-sm font-medium {{ $done ? 'text-ink' : 'text-ink-3' }}">{{ $label }}</p>
                            <p class="text-xs text-ink-3">{{ $description }}</p>
                        </div>
                    </li>
                @endforeach
            </ol>

            @if ($generation->status === AiGenerationStatus::Failed)
                <x-ui.alert tone="danger" class="mt-4" title="Generation failed">
                    {{ $generation->validation_error }}
                    <p class="mt-1 text-xs">
                        The record is kept deliberately — a failure is provenance too, and usually the
                        case most worth reading.
                    </p>
                </x-ui.alert>
            @endif
        </x-ui.card>
    </div>

    @if ($generation->approval)
        <x-ui.card title="Decision" class="mb-5">
            <div class="flex flex-wrap items-center gap-3">
                <x-ui.status-badge :status="$generation->approval->decision" />
                <span class="text-sm text-ink-2">
                    {{ $generation->approval->decidedBy?->name }}
                </span>
                <span class="text-xs text-ink-3">
                    {{ $generation->approval->decided_at?->format('d M Y H:i') }}
                </span>
            </div>

            @if ($generation->approval->remark)
                <p class="mt-2 text-sm text-ink-2">{{ $generation->approval->remark }}</p>
            @endif

            <p class="mt-3 border-t border-line pt-3 text-xs text-ink-3">
                One decision per generation. Reversing a judgement means generating again, so the original
                and who made it stay on the record.
            </p>
        </x-ui.card>
    @endif

    <div class="grid gap-5 xl:grid-cols-2">
        <x-ui.card title="Proposed output" subtitle="Data, never executed.">
            @if ($generation->validated_output)
                <pre class="max-h-96 overflow-auto rounded-md bg-canvas p-3 text-xs leading-relaxed text-ink-2 ring-1 ring-inset ring-line">{{ json_encode($generation->validated_output, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre>
            @elseif ($generation->raw_output)
                <p class="mb-2 text-xs text-ink-3">
                    Raw output — it did not validate against the schema, so it was never persisted as
                    structure and never reached the form engine.
                </p>
                <pre class="max-h-96 overflow-auto rounded-md bg-elevated p-3 text-xs leading-relaxed text-ink-2">{{ $generation->raw_output }}</pre>
            @else
                <x-ui.empty title="Nothing came back"
                            description="The provider call did not return usable text. The attempt is still recorded." />
            @endif
        </x-ui.card>

        <x-ui.card title="Context the model saw" subtitle="Written once. Never read back into business logic.">
            <pre class="max-h-96 overflow-auto rounded-md bg-raised p-3 text-xs leading-relaxed text-ink-2 ring-1 ring-inset ring-line">{{ json_encode($generation->input_context, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre>

            <p class="mt-3 text-xs text-ink-3">
                Assembled at call time from this business's own records only. Text a participant wrote is
                carried as clearly-marked quoted material and never as instruction.
            </p>
        </x-ui.card>
    </div>

    @if ($generation->resultingFormVersion)
        <x-ui.card title="Resulting form version" class="mt-5">
            <div class="flex flex-wrap items-center justify-between gap-3">
                <div>
                    <p class="text-sm font-medium">
                        {{ $generation->resultingFormVersion->formTemplate?->name }}
                        — v{{ $generation->resultingFormVersion->version_number }}
                    </p>
                    <p class="text-xs text-ink-3">
                        Built through the ordinary form engine, so it is answered and scored by exactly the
                        same code as a hand-authored form.
                    </p>
                </div>

                <x-ui.status-badge :status="$generation->resultingFormVersion->status" />
            </div>
        </x-ui.card>
    @endif

    <x-ui.modal :show="$drafting" title="Create a draft form version" close="$set('drafting', false)">
        <form wire:submit="draft" class="space-y-4">
            <x-ui.field label="Form template" required
                        hint="The draft becomes the next version of this template. Only shared curriculum and this customer's own templates are offered."
                        :error="$errors->first('draftTemplateId')">
                <x-ui.select wire:model="draftTemplateId">
                    <option value="">Choose a template…</option>
                    @foreach ($templates as $template)
                        <option value="{{ $template->id }}">{{ $template->name }}</option>
                    @endforeach
                </x-ui.select>
            </x-ui.field>

            <x-ui.alert tone="info">
                This creates a <strong>draft</strong> and nothing more. It is not published, and it cannot
                be published until somebody other than you approves the generation.
            </x-ui.alert>

            <div class="flex justify-end gap-2">
                <x-ui.button type="button" wire:click="$set('drafting', false)">Cancel</x-ui.button>
                <x-ui.button variant="primary" type="submit">Create draft</x-ui.button>
            </div>
        </form>
    </x-ui.modal>

    <x-ui.modal :show="$deciding" title="Review AI output" close="$set('deciding', false)">
        <p class="text-sm text-ink-2">
            Approving publishes whatever draft this generation produced, credited to you. Rejecting leaves
            the draft unpublished; it is not deleted.
        </p>

        <x-ui.field label="Remark" class="mt-4" hint="Required when rejecting." :error="$errors->first('remark')">
            <x-ui.textarea wire:model="remark" rows="3" />
        </x-ui.field>

        <x-slot:footer>
            <x-ui.button wire:click="$set('deciding', false)">Cancel</x-ui.button>
            <x-ui.button wire:click="reject">Reject</x-ui.button>
            <x-ui.button variant="primary" wire:click="approve">Approve</x-ui.button>
        </x-slot:footer>
    </x-ui.modal>
</div>
