<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * What was actually DELIVERED - file, format, parameters, checksum,
     * generator, timestamp.
     *
     * WHY PERSIST THE FILE AT ALL: regenerating a report tomorrow gives
     * different numbers, because the operational data underneath it has moved.
     * "What did we tell them before Session 1?" has to stay answerable, and
     * only the bytes that were handed over can answer it.
     *
     * IMMUTABLE, AND NEVER A QUERY SOURCE. Reports are queries over
     * operational data; this table stores what was issued and nothing else.
     * No part of the application reads a figure back out of an artifact - a
     * test asserts it.
     *
     * NO UNIQUE KEY. The same report is legitimately generated repeatedly, and
     * each generation is its own delivered artifact with its own checksum.
     */
    public function up(): void
    {
        Schema::create('report_artifacts', function (Blueprint $table) {
            $table->id();

            // diagnostic | participant_progress | batch_summary |
            // attendance_register | assignment_status. Validated in
            // application code: a native ENUM is not portable between SQLite
            // and MySQL.
            $table->string('report_key', 60);

            // The enrolment or batch this report is about. Polymorphic, so no
            // foreign key; the subject's customer is resolved server-side by
            // SubjectOwnership before anything is generated.
            $table->string('subject_type', 100);
            $table->unsignedBigInteger('subject_id');

            // pdf | csv.
            $table->string('format', 10);

            $table->string('disk', 30)->default('local');
            $table->string('path', 500);

            // The filters that produced it. Without them, a stored file cannot
            // be explained a year later.
            $table->text('parameters')->nullable();

            // Proof the file is the one that was issued.
            $table->char('checksum_sha256', 64);

            // Null when generated by the scheduler rather than by a person.
            $table->foreignId('generated_by')->nullable()->constrained('users')->restrictOnDelete();
            $table->timestamp('generated_at');

            $table->timestamps();

            // "Every report ever issued about this enrolment."
            $table->index(['subject_type', 'subject_id', 'report_key']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('report_artifacts');
    }
};
